### ISSUE TITLE
Requirements capacity/license

### ISSUE THREAD

**Issue by mschindl** [NetAppDocs/ontap-select#106]
Page: [Remote and branch office](https://docs.netapp.com/us-en/ontap-select/concept_usecase_robo.html)
Page: [ONTAP Select two-node clusters with HA](https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_two_node.html)

Hello,
I checked the docs and ask me where I can find the information about MINIMUM CAPACITY for license and logical/physical disk requirements for Two-node cluster with HA capability. Same request could be for single node.

Brgds, Marc

**Comment by dmp-netapp** [comment]
Marc, thanks for your feedback. We will review and update the site. -David

**Comment by dmp-netapp** [comment]
Hi Marc,

I looked at your comment, and believe your answer regarding minimum storage is here:

    https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_storage.html

Scroll down to the section “Storage capacity restrictions”.

Also, regarding the minimum that must be purchased, see the capacity tiers and capacity pools section here:

    https://docs.netapp.com/us-en/ontap-select/concept_lic_production.html

Please let me know if you have any other questions.

David

**Comment by mschindl** [comment]
Thank you
