### ISSUE TITLE
Feedback from David Hepler regarding VMWare support

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-select#121]
Page: [VMware hypervisor and hardware considerations](https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_hardware.html)

From: Hepler, David <David.Hepler@netapp.com> 
Sent: 07 July 2020 14:20
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: saasdocs_feedback: https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_hardware.html#core-hardware-requirements

VMWare no longer supports „VMware ESXi 6.0 GA (build 2494585 or greater)“  - (See https://kb.vmware.com/s/article/66977)
Do we really still support that?

David

**Comment by dmp-netapp** [comment]
I have already removed ESXi 6.0. Closing this issue,
