### ISSUE TITLE
Feedback on vCenter access rights information

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-select#122]
Page: [Required information for ONTAP Select installation](https://docs.netapp.com/us-en/ontap-select/reference_chk_select_req_info.html)
-----------------------------
From: Hepler, David <David.Hepler@netapp.com> 
Sent: Tuesday, July 28, 2020 3:43 AM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: saasdocs_feedback: https://docs.netapp.com/us-en/ontap-select/reference_chk_select_req_info.html#cluster-level-information

I was using search to look for vCenter access rights. I found a link in the FAQ that sent me to this page, which is wrong:
https://docs.netapp.com/us-en/ontap-select/reference_chk_select_req_info.html#access-to-a-vcenter-server

Best Regards,
David Hepler

**Comment by dmp-netapp** [comment]
I corrected this.

**Comment by dmp-netapp** [comment]
Actually the link I corrected is in the FAQ section. I do not see any mention of vCenter rights on this page. But I will add to a page above it in the same section, which seems more appropriate.
