### ISSUE TITLE
typo in cmd

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/ontap-select#133]
Page: [Recovering the Deploy utility for a two-node cluster](https://docs.netapp.com/us-en/ontap-select/task_cli_deploy_recover_two_node.html)

There is a typo in the following cmd syntax:
disk show --container-type mediator << wrong
disk show -container-type mediator << corrected

**Comment by dmp-netapp** [comment]
I need to verify this change.

**Comment by dmp-netapp** [comment]
This is now fixed. Closing the issue.
