### ISSUE TITLE
Correcting terms and clairifying ESXi

### ISSUE THREAD

**Issue by texanerinbayern** [NetAppDocs/ontap-select#148]
Page: [Networking considerations](https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_networking.html)

The term vSphere talks about the entire virtualization platform from VMWare. vCenter is the management server used to manage the ESXi hosts. If there is no vCenter, then the ESX host is "unmanaged".

I am not sure if a "/" or an "or" is better here, as it is not both but one or the other.

TLS (443) | Deploy to vCenter/ESXi (Unmanaged) | VMware VIX API
-- | -- | --
902 | Deploy to vCenter/ESXi (Unmanaged) | VMware VIX API

**Comment by dmp-netapp** [comment]
I made the change to differentiate managed versus unmanaged:

"Deploy to either vSphere (managed) or ESXi (unmanaged)"

Expect to push to live public site today.

**Comment by dmp-netapp** [comment]
The change is now live. Used "vCenter server" instead of "vSphere". Closing issue.
