### ISSUE TITLE
Correct 2 errors

### ISSUE THREAD

**Issue by texanerinbayern** [NetAppDocs/ontap-select#149]
Page: [Physical switch configuration](https://docs.netapp.com/us-en/ontap-select/concept_nw_physical_switch_config.html)

1st Change: Add a dash between non and routable
2nd Change: Remove the dangling "Best Practice" from the end of the paragraph after "are unsupported."

ONTAP Select internal network traffic occurs using virtual interfaces defined with link local IP addresses. Because these IP addresses are non-routable, internal traffic between cluster nodes must flow across a single layer-2 network. Route hops between ONTAP Select cluster nodes are unsupported.

**Comment by dmp-netapp** [comment]
I have updated the page to make two corrections. Expect this will be live later tonight and so please confirm tomorrow (Dec 2).

**Comment by dmp-netapp** [comment]
The change is now live. Closing issue.
