### ISSUE TITLE
Ports e0c and e0g mixed up

### ISSUE THREAD

**Issue by Myer** [NetAppDocs/ontap-select#152]
Page: [Single and multiple node network configurations](https://docs.netapp.com/us-en/ontap-select/concept_nw_single_multi_node.html)

For single nodes here (https://docs.netapp.com/us-en/ontap-select/concept_nw_single_multi_node.html#lif-assignment) it says:

> Management and data LIFs (e0a, e0b, and **_e0c_**)
> ONTAP ports e0a, e0b, and **_e0g_** are delegated as candidate ports for LIFs that carry the following types of traffic

I think e0g is a typo and should be e0c. On my recently deployed ONTAP Select single node cluster only ports e0a, e0b and e0c were created, there was no e0g.

**Comment by dmp-netapp** [comment]
Thanks. NetApp had a company shutdown for the last ten days. Will look at this issue today.

**Comment by dmp-netapp** [comment]
I updated the content to correct the typo. It's now live.

**Comment by dmp-netapp** [comment]
Closing.
