### ISSUE TITLE
ONTAP Select versions need to be updated to included latest version / current verison

### ISSUE THREAD

**Issue by texanerinbayern** [NetAppDocs/ontap-select#155]
Page: [Storage efficiency support](https://docs.netapp.com/us-en/ontap-select/concept_stor_eff_support.html)

Versioning needs to be updated in multiple places, for example "9.6 All Licenses" should be something like "9.6 and newer - All licenses"

**Comment by dmp-netapp** [comment]
Thanks. I am reviewing now. Question: is the "starting issue" always 9.6?

**Comment by texanerinbayern** [comment]
I believe a number of the storage efficiency changes came with 9.6. The more I look at that big table the more confusing it is... I would almost consider removing everything that is for older than 9.6 (9.5 is going end of support at the end of this month, I believe). In fact, since this is the documentation for 9.10.x it might make sense just to include what currently is supported, or n-1, or at least say since 9.5/6 to current.

**Comment by dmp-netapp** [comment]
Thanks. I was out yesterday. Will look at this again

**Comment by dmp-netapp** [comment]
I will resolve the issue this week. Sorry for the delay.

**Comment by dmp-netapp** [comment]
I have some questions open now for product management. After I get a response, will be able to update the content.

**Comment by dmp-netapp** [comment]
Just sent DH an email. Will wait for his response before proceeding.

**Comment by dmp-netapp** [comment]
The doc has been updated for 9.11.1 and is now live. I expect to look at this issue again next week.

**Comment by dmp-netapp** [comment]
Sorry for the delay. I will resume work on this soon.

**Comment by ntap-bmegan** [comment]
@dmp-netapp - Is this work complete? If not, can you provide an estimate?

**Comment by dmp-netapp** [comment]
Not completed. Ed and Aksel are considering moving ONTAP Select to another writer, given my other responsibilities. Will check with them about this and the open issues, including this one.

**Comment by netapp-ehoffman** [comment]
This "deep-dive" content is also covered in the legacy ONTAP Select TR at https://www.netapp.com/media/10662-tr4517.pdf. I'd suggest we assign this to the Bard team: remove all references in this table to 9.5 and lower and point users to the legacy TR for reference content about versions of ONTAP Select 9.5 and lower. That way, we can streamline the table to simply refer to different media types (DAS SSD, DAS HDD, and vNAS). (Columns 2 and 5 would go away entirely. Other columns would just refer to ONTAP Select 9.6 and higher.) Could expand this same approach to any other references in the deep-dive sections to 9.5 and lower.

**Comment by netapp-powr** [comment]
Some changes were made in #186. As you can see, versioning was updated to the 9.6 release and the table was simplified, as requested by @netapp-ehoffman. However, some questions remain about the accuracy of this legacy content.

For example, were any storage efficiency features added, removed, or defaults modified in any post-9.6 release? 

Does this footnote apply equally well to post-9.6 releases?

> ONTAP Select 9.6 supports a new license (premium XL) and a new VM size (large). However, the large VM is only supported for DAS configurations using software RAID. Hardware RAID and vNAS configurations are not supported with the large ONTAP Select VM in the 9.6 release.

Does the upgrade behavior for DAS SSD/HDD configurations remain the same?
