### ISSUE TITLE
Workflow for adding license renewals

### ISSUE THREAD

**Issue by daverclarke** [NetAppDocs/ontap-select#156]
Page: [ONTAP Select licenses](https://docs.netapp.com/us-en/ontap-select/task_adm_licenses.html)

Can the page get an update around how to apply license renewals, even if it's just a note stating to use "add".

**Comment by dmp-netapp** [comment]
Thanks for your feedback. Looking at this now.

**Comment by dmp-netapp** [comment]
I updated the task based on what you suggested in the associated pull request. The change is live. The text for the step now begins: "To add a new license or renew an existing license, click ...".

**Comment by daverclarke** [comment]
Thanks, that clears up the process.

**Comment by dmp-netapp** [comment]
Closing.
