### ISSUE TITLE
Add remark that following Resizing of VM Instance is supported only for Capacity Tier License Type . 

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap-select#159]
Page: [Resizing the ONTAP Select cluster nodes](https://docs.netapp.com/us-en/ontap-select/task_adm_resize.html)

We should add a comment on this page that this is supported only for Capacity Tiers License Type.

**Comment by dmp-netapp** [comment]
Thanks for the feedback. I will review and update.

**Comment by dmp-netapp** [comment]
I updated the page and it is now live.

**Comment by dmp-netapp** [comment]
The change is live. Closing.
