### ISSUE TITLE
Wrong CLI

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-select#163]
Page: [Replacing a failed drive when using SW RAID](https://docs.netapp.com/us-en/ontap-select/task_adm_replace_drives_swraid.html)

Regarding:
________________________________________________________________________
**Identify the failed drive**

After a drive fails, use the **Deploy utility CLI** to identify the disk that failed.
Steps

    Sign in to the **Deploy utility CLI** using the administrator account.

    Identify the disk that has failed.

`    <cluster name>::> storage disk show -container-type broken`
_________________________________________________________________________

That sure looks like the **_ONTAP CLI_** (the **_Cluster CLI_**), not the Deploy CLI...
(Wrong prompt, should be "(ONTAPdeploy) ", wrong command [`node storage disk` ... might get you somewhere...])

Greetings from Northfriesland

Sebastian 
NAI

**Comment by dmp-netapp** [comment]
We appreciate your feedback. Reviewing now.

**Comment by dmp-netapp** [comment]
I changed to ONTAP CLI. The update is live. Will close this issue soon.
