### ISSUE TITLE
See Before you begin to prepare to deploy the cluster. 

### ISSUE THREAD

**Issue by charlesmorrall** [NetAppDocs/ontap-select#164]
Page: [Deploying an ONTAP Select cluster](https://docs.netapp.com/us-en/ontap-select/task_deploy_cluster.html)

Check the section "See [Before you begin](http://task_deploy_cluster.html/#before-you-begin) to prepare to deploy the cluster."

The hyperlink only points to the html file, not the full URL.

**Comment by dmp-netapp** [comment]
We appreciate your feedback. Reviewing now.

**Comment by dmp-netapp** [comment]
Have corrected the link. This will go live shortly with the updated 9.11.1 doc.

**Comment by dmp-netapp** [comment]
This issue has been fixed and now live.
