### ISSUE TITLE
End-to-End management would also include starting/stopping/deleting a Cluster...

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-select#165]
Page: [Automate ONTAP Select deployments with Ansible](https://docs.netapp.com/us-en/ontap-select/concept_automate_ansible.html)

I'm advocating for an additional variable, e.g.

> **cluster_state**

with the possible values:

> **started (default)**
> stopped
> absent

This way we could implement an actual end-to-end lifecycle management:

- Deploy (or start from a "stopped" state) -> cluster_state = "started"
- Stop -> cluster_state = "stopped"
- Delete -> cluster_state = "absent"

Should not be too hard to implement, I think. But I'm new to Ansible.
Small change but powerful, I think.

(I wrote a 3-day training about ONTAP Select and the last Module (and exercise) is about automation and I roll out Deploy, roll out a cluster, roll out SVM/share/export and wanted to roll everything back also. The "cluster undeploy" capability is missing...
https://www.flane.de/en/course/fl-ots
)

Greetings from Northfriesland

Sebastian

**Comment by dmp-netapp** [comment]
Thanks for your feedback. Reviewing.

**Comment by dmp-netapp** [comment]
We are evaluating this feature for a future release.

**Comment by dmp-netapp** [comment]
To repeat, we are evaluating this enhancement for a future release. No decision has been made, but product management and engineering are aware of the request. Given that nothing further can be done now, I will close this issue. When I received more specific details I can re-open this issue. Thanks.
