### ISSUE TITLE
Kebab Menu? I'm getting hungry...

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-select#168]
Page: [ONTAP Select Release Notes](https://docs.netapp.com/us-en/ontap-select/reference_release_notes.html)

To be exact: from there, go to the **ONTAP Select 9.11.1 release notes, page 20:**

Bug 1447383
After an ONTAP Deploy upgrade, run CC from the **cluster create operations _kebab_ menu**.

"pop-up menu"?
Fancy local name for the "Hamburger Menu" (the "3 dashes")?

Greetings from Northfriesland

Sebastian

**Comment by dmp-netapp** [comment]
Thanks for the feedback. Reviewing now.

**Comment by dmp-netapp** [comment]
This involves the description in a fixed issued. For simplicity, removed the word "kebab". The updated release nots pub is now live. Will close this issue soon.

**Comment by dmp-netapp** [comment]
Closing.
