### ISSUE TITLE
Missing hyperlink

### ISSUE THREAD

**Issue by pgbachman** [NetAppDocs/ontap-select#169]
Page: [ONTAP Select licenses](https://docs.netapp.com/us-en/ontap-select/task_adm_licenses.html)

In the section "Reinstalling a capacity pool license", Step 2 has italicized text "Acquiring a capacity pool license" to direct the user. It should be hyperlinked to    https://docs.netapp.com/us-en/ontap-select/task_lic_acquire_cp.html

**Comment by dmp-netapp** [comment]
Thanks for the feedback. Reviewing this now.
