### ISSUE TITLE
This page requires review

### ISSUE THREAD

**Issue by texanerinbayern** [NetAppDocs/ontap-select#171]
Page: [VMware vCenter server](https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_vcenter.html)

Hi all!

This page requires review. We recently had customers creating a user following this guide and it seems some of the names or rights have changed and not everything matched up, so it would probably make sense to make sure the user settings match with the newest version of VMWare.

Cheers,
David

**Comment by dmp-netapp** [comment]
Thanks. Reviewing now. Will need to reach out to development.

**Comment by dmp-netapp** [comment]
Development is reviewing this now. No estimate yet for an update.

**Comment by dmp-netapp** [comment]
This page has been reorganized slightly as part of a recent accessibility update. Development is reviewing the content and I expect more details soon (probably early next week).

**Comment by ntap-bmegan** [comment]
@dmp-netapp - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @texanerinbayern - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @akseldavis

**Comment by dmp-netapp** [comment]
I am finally beginning to move off ONTAP Select with 9.12.1 due to other work. But I will check this week for any information I might have that can restart this issue and bring it to closure.

**Comment by ntap-bmegan** [comment]
Thanks, @dmp-netapp. Alternately, if you are able to assign it to someone else, go ahead and do so.

**Comment by netapp-thomi** [comment]
@texanerinbayern   Hi David,
The process was reviewed by development:   Here is their response:
--------------------------
We have not changed  any Privileges for a user. And we verified with the latest vcenter version [vcenter 7.0U3 GA], that all the tabs and  user settings are available as per the document.

VMware vCenter server ([netapp.com](http://netapp.com/))<https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_vcenter.html#host>.

I'm going to close this issue.  If your customer is still having issues with user settings/privileges, you might consider opening a support ticket or BURT.

Thanks,
Thom
