### ISSUE TITLE
S3 is missing

### ISSUE THREAD

**Issue by texanerinbayern** [NetAppDocs/ontap-select#172]
Page: [ONTAP features enabled by default](https://docs.netapp.com/us-en/ontap-select/reference_lic_ontap_features.html)

ONTAP S3 is missing from the supported features (master key available at zero cost).

Cheers,
David

**Comment by dmp-netapp** [comment]
Thanks. Reviewing now.

**Comment by dmp-netapp** [comment]
I added ONTAP S3. The update is live. Will close this issue soon.
