### ISSUE TITLE
Add all the possibilities for network ports

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/ontap-select#174]
Page: [VMware hypervisor and hardware considerations](https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_hardware.html)

Hi,

This page does not mention 25GB & 40GB ports, whereas the following link does:
https://docs.netapp.com/us-en/ontap-select/concept_nw_supported_configs.html

It would be great to have coherency between both pages, so that customers dont have to browse multiple pages to find the right information

thanks

**Comment by dmp-netapp** [comment]
Thanks for your feedback. Reviewing this issue.
