### ISSUE TITLE
9.9 and 9.10 Select release notes dont show the actual step upgrades for Select

### ISSUE THREAD

**Issue by chuffster80** [NetAppDocs/ontap-select#178]
Page: [Upgrading the ONTAP Select nodes](https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html)

I've noticed the release notes link on pg5 under ONTAP Select upgrade and support about the upgrade paths for Deploy are shown but not for Select itself.
https://library.netapp.com/ecm/ecm_download_file/ECMLP2879854

If a customer looks at this wanting to figure out how to go from say 9.7 Select to 9.10, the document doesnt include which versions of Select to step up to, and only seems to imply the upgrade step up for Deploy.

Example from the document
Upgrading to ONTAP Select 9.10.1 Deploy from ONTAP Select 9.7 or Deploy 2.12
If you are using ONTAP Select 9.7 or Deploy 2.12, upgrading directly to ONTAP Select 9.10.1 is not supported.
You can do the following:
1. Upgrade to ONTAP Select 9.8 Deploy.
2. Upgrade to ONTAP Select 9.10.1 Deploy

Where in the above steps does it show the steps needed (direct/multi hop) for the required version(s) of Select?

Unless I'm missing something in the doc for what versions of Select to upgrade to or skip from one version to the next, this may confuse customers about the upgrade process, implying you only need to upgrade Deploy.

Same is also noted in the 9.9.1 release notes. We seem to only show what versions of Deploy you can upgrade to, but not the Select version.

**Comment by dmp-netapp** [comment]
The procedure to upgrade ONTAP Select nodes is included in the core web doc. You can copy/paste the following link into your browser to see it:

https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html

We are considering options to make customers more aware of this.

**Comment by chuffster80** [comment]
Hi David,

Thanks for the follow up.

Yes I did see that info here.
I have had to go in for customers in the recent past to help them figure out what step upgrades need to be performed for Deploy and Select (example getting from 9.3 to 9.9.1) which took a while.

Those pdf links that show the step upgrade for Deploy are great, but the customer asked “why doesn’t it show the Select step upgrade and when do I upgrade it after step upgrading Deploy?”  That kind of thing.

So then I have to figure out by switching back and forth between the ONTAP upgrade compatibility link back over to the release notes for Deploy to piece this stuff together.



Best Regards,


Chris Huff
Technical Support Engineer 3
Technical Support Center
***@***.******@***.***>

***@***.***

[Text  Description automatically generated]<https://www.netapp.com/pdf.html?item=/media/31983-DS-4141-NA-Cloud-TAM.pdf>

[Icon  Description automatically generated with medium confidence]<https://www.facebook.com/NetApp>   [Icon  Description automatically generated] <https://www.instagram.com/netapp/>    [Icon  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing text, clipart  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing text, ax, gear  Description automatically generated] <https://twitter.com/NetApp>

**Comment by ntap-bmegan** [comment]
@dmp-netapp - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @chuffster80 - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @akseldavis

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: [Upgrading a Deploy instance](https://docs.netapp.com/us-en/ontap-select/task_cli_upgrade_deploy.html)
