### ISSUE TITLE
Network configuration best practices link is broken

### ISSUE THREAD

**Issue by roscocheeta** [NetAppDocs/ontap-select#180]
Page: [Frequently asked questions](https://docs.netapp.com/us-en/ontap-select/reference_faq.html)

The link for "Network configuration best practices" on this doc is broken. It refers to https://docs.netapp.com/us-en/ontap-select/ct_nw_supported_configuraitons.html#network-configuration-best-practices

**Comment by dmp-netapp** [comment]
Thanks for your feedback. We are reviewing this now.

**Comment by dmp-netapp** [comment]
The link has been corrected. The update is live. I will leave this issue open for a day or two. Thanks.

**Comment by dmp-netapp** [comment]
I fixed this a while back. Closing.
