### ISSUE TITLE
Can we have 9.9.1, 9.10.1 or above performance reference docs for this

### ISSUE THREAD

**Issue by zhihongluo** [NetAppDocs/ontap-select#182]
Page: [ONTAP Select 9.6 performance: Premium HA direct-attached SSD storage](https://docs.netapp.com/us-en/ontap-select/concept_perf_premium_ha_direct_ssd_96.html)

**Comment by dmp-netapp** [comment]
Thanks for your feedback. We are reviewing.

**Comment by dmp-netapp** [comment]
Sorry for the delay. Will review this again in the next week.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: [Performance: Premium HA direct-attached SSD storage](https://docs.netapp.com/us-en/ontap-select/concept_perf_premium_ha_direct_ssd_96.html)
