### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by chrisgeb** [NetAppDocs/ontap-select#185]
Page: [Where to get help and find more information](https://docs.netapp.com/us-en/ontap-select/reference_additional_info.html)

[NetApp ONTAP Select resources](https://www.netapp.com/data-management/software-defined-storage-ontap-select/documentation) returns 404...  I believe it should take you to this page https://www.netapp.com/data-management/ontap-select/documentation/

**Comment by dmp-netapp** [comment]
Thanks. I have informed the IE team.

**Comment by netapp-powr** [comment]
Fixed ✔️
