### ISSUE TITLE
Outdated sys req's

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/ontap-select#189]
Page: [Storage and RAID considerations](https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_storage.html)

- ESXi 6.5 U2 (build 8294253) or later
- ESXi 6.7 GA (build 8169922) or later

These are out of date.

External storage support information is also missing.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - Thanks for your feedback. We will look into your request and update you here.
Thank you for helping us to improve our documentation.

**Comment by netapp-cgoff** [comment]
Hi @netapp-chandaj - this issue is still in progress. 
We will update with more soon. 
Thanks!

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here:
https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_storage.html
https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_storage.html#general-requirements
