### ISSUE TITLE
There is no description about Anti-Ransomware Protection feature.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap-select#190]
Page: [ONTAP features](https://docs.netapp.com/us-en/ontap-select/reference_lic_ontap_features.html)

Please state if Anti-Ransomware Protection feature is supported.

**Comment by netapp-pcarriga** [comment]
@kanitani - Thanks for your feedback. We will look into your request and update you here.
Thank you for helping us to improve our documentation.

**Comment by netapp-thomi** [comment]
ARP is NOT supported in ONTAP Select.   A note will be added to the documentation to this effect.  This issue is now being tracked in ONTAPDOC-807.    Thanks for bringing this concern to our attention.
