### ISSUE TITLE
NetApp Volume Encryption listed twice in the section "ONTAP features automatically enabled by default"

### ISSUE THREAD

**Issue by netappacook** [NetAppDocs/ontap-select#192]
Page: [ONTAP features](https://docs.netapp.com/us-en/ontap-select/reference_lic_ontap_features.html)

NetApp Volume Encryption listed twice in the section "ONTAP features automatically enabled by default".   Please remove the line that does not include the comment about "non-restricted countries". 

    NFS

    CIFS

    iSCSI

    SnapMirror

    SnapVault

    FlexClone

    SnapRestore

    **NetApp Volume Encryption**

    Deduplication and compression

    ONTAP multitenancy capability

    ONTAP S3

    **NetApp Volume Encryption (non-restricted countries only)**

**Comment by netapp-powr** [comment]
@netappacook - Is this the change that needs to be made?

https://github.com/NetAppDocs/ontap-select/pull/193/files

**Comment by netappacook** [comment]
Yes, that's the correct change. Thanks.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: [ONTAP features](https://docs.netapp.com/us-en/ontap-select/reference_lic_ontap_features.html)
