### ISSUE TITLE
Capacity pool expiry

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/ontap-select#196]
Page: [ONTAP Select licenses](https://docs.netapp.com/us-en/ontap-select/task_adm_licenses.html)

Can we please document the side effects of what will happen when a capacity pool license expires?

**Comment by sabarig84** [comment]
can someone look into this?

**Comment by dmp-netapp** [comment]
Thanks for the feedback. We are reviewing.

**Comment by netapp-thomi** [comment]
Tracking the progress of this issue in Jira ONTAPDOC-885

**Comment by sabarig84** [comment]
folks, can we please expedite this?

**Comment by netapp-thomi** [comment]
A paragraph was added to the end of the following topic, explaining that nothing happens when license expires, but license renewal should be expedited.
ontap-select/task_adm_licenses.html#managing-the-capacity-tier-licenses
