### ISSUE TITLE
Host configuration and preparation checklist

### ISSUE THREAD

**Issue by pbNetApp** [NetAppDocs/ontap-select#197]
Page: [Host configuration and preparation checklist](https://docs.netapp.com/us-en/ontap-select/reference_chk_host_prep.html)

vSwitch is set to Active-Active but according to TR4517 port groups are set to Active-Standby

**Comment by netapp-pcarriga** [comment]
@pbNetApp - Thank you for your feedback. We will review and update the documentation accordingly.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation [here](https://docs.netapp.com/us-en/ontap-select/reference_chk_host_prep.html#vswitch-configuration-on-a-hypervisor-host).
