### ISSUE TITLE
Need to include information on backing up the ONTAP Select Deploy configuration database in the documentation

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap-select#202]
Page: [ONTAP Select documentation](https://docs.netapp.com/us-en/ontap-select/index.html)

There appears to be no mention of the _deploy backup create_ command in the ONTAP Select documentation to backup the ONTAP Select deploy configuration database prior to an upgrade or as part of a best practice on backing up the ONTAP Select Deploy VM.  This is covered in this KB articlehttps://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_Select/How_to_Backup_and_Restore_the_ONTAP_Select_Deploy_VM and lightly touched on in the best practice TR (page 56 - https://www.netapp.com/media/10662-tr4517.pdf).  This information should be included in the main ONTAP Select documentation as well.

**Comment by netapp-pcarriga** [comment]
Hi @DrKeno - Thanks for your feedback. We will look into your request and update you here.
Thank you for helping us to improve our documentation.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This is addressed in our documentation here: [Migrating a Deploy instance to a new virtual machine](https://docs.netapp.com/us-en/ontap-select/task_cli_migrate_deploy.html#backing-up-the-deploy-configuration-data)

If you have any other questions about this then please do follow up, thanks!
