### ISSUE TITLE
incorrect contact email

### ISSUE THREAD

**Issue by vgeert** [NetAppDocs/ontap-select#207]
### Page URL

https://docs.netapp.com/us-en/ontap-select/reference_faq.html

### Page title

Frequently asked questions

### Summary

Where do I get clarification for questions not covered in this FAQ?

This email address listed here is not for external use

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dmp-netapp** [comment]
We believe that we've resolved this issue. Please try again and send an email to the same address.

**Comment by ntap-bmegan** [comment]
@dmp-netapp - I've sent a test of the link from my personal tablet. Please confirm with the team that monitors the email that it was received and then close this issue or take further action.

**Comment by dmp-netapp** [comment]
@ntap-bmegan I am not working with ONTAP Select any longer. But will follow up with the team that does.

**Comment by dmp-netapp** [comment]
@ntap-bmegan Reviewed this again. I am actually still on the list, with a rule sending emails to a dedicated folder. Scrolled down in the folder about two weeks and I see your email :) Will forward to you just FYI and will close this issue later today. Thanks.

**Comment by dmp-netapp** [comment]
Closing.
