### ISSUE TITLE
warning about changing initial setup

### ISSUE THREAD

**Issue by vgeert** [NetAppDocs/ontap-select#208]
### Page URL

https://docs.netapp.com/us-en/ontap-select/reference_initial_state.html

### Page title

Initial state of the cluster after deployment

### Summary

We should stress here not to edit/adjust the user roles/permissions. This due to KB: 
https://kb.netapp.com/onprem/ontap/ONTAP_Select/OTS_Deploy_cluster_refresh_fails_with_error%3A_ONTAPSelectSysCLIVersionFailed_zapi_returned_bad_status_0%3A_None

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here:
https://docs.netapp.com/us-en/ontap-select/reference_initial_state.html
