### ISSUE TITLE
The note about license types and resizing is not correct

### ISSUE THREAD

**Issue by RobertBlackhart** [NetAppDocs/ontap-select#210]
### Page URL

https://docs.netapp.com/us-en/ontap-select/task_adm_resize.html

### Page title

Resizing the ONTAP Select cluster nodes

### Summary

On the page, there is a note that says `You can only perform the cluster nodes resizing operation when using the capacity tiers licensing model. ONTAP Select nodes that have a capacity pools license cannot be resized.`. This is not a correct statement. Both the capacity tiers model and the capacity pools model allow for resizing nodes.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here:
https://docs.netapp.com/us-en/ontap-select/task_adm_resize.html
