### ISSUE TITLE
VMWare should be capitalized VMware

### ISSUE THREAD

**Issue by netapp-chrisgeb** [NetAppDocs/ontap-select#213]
### Page URL

https://docs.netapp.com/us-en/ontap-select/concept_nw_vsphere_vswitch_config.html

### Page title

VMWare vSphere vSwitch Configuration

### Summary

VMWare should be capitalized VMware in both the adoc page and the sidebar page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: 
[VMware vSphere vSwitch Configuration](https://docs.netapp.com/us-en/ontap-select/concept_nw_vsphere_vswitch_config.html)
[Supported network configurations](https://docs.netapp.com/us-en/ontap-select/concept_nw_supported_configs.html)
