### ISSUE TITLE
Please add ONTAP Select VM be backed up with VMware or other third-party snapshots are not supported and will not work when trying to recover. 

### ISSUE THREAD

**Issue by pbNetApp** [NetAppDocs/ontap-select#215]
### Page URL

https://docs.netapp.com/us-en/ontap-select/reference_plan_best_practices.html

### Page title

Summary of best practices

### Summary

Backing up ONTAP Select vm's:

ONTAP Select VM should not be backed up with VMware or other third-party snapshots and are not supported and will not work when trying to recover. 

The ONTAP Select VM uses independent-persistent drives, which are excluded from VMware-based snapshots. The only supported method for backing up ONTAP Select is SnapMirror, SnapVault, or SVM DR (where applicable).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. There was no change made to the **Best Practices** topic as this issue is addressed in our documentation here: 
https://docs.netapp.com/us-en/ontap-select/reference_faq.html#general 

Please reach out if you've any further questions, thank you!
