### ISSUE TITLE
no 2-node instructions

### ISSUE THREAD

**Issue by jmaciosz** [NetAppDocs/ontap-select#216]
### Page URL

https://docs.netapp.com/us-en/ontap-select/task_deploy_cluster.html

### Page title

Deploying an ONTAP Select cluster

### Summary

the beginning of the document describes creating one-node and two-node clusters.  however this page (or any subsequent page) do not contain the instructions for creating two-node clusters.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here:
https://docs.netapp.com/us-en/ontap-select/task_deploy_cluster.html#creating-a-single-node-or-multi-node-cluster
