### ISSUE TITLE
not supported features missing

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/ontap-select#219]
### Page URL

https://docs.netapp.com/us-en/ontap-select/concept_ots_overview.html

### Page title

ONTAP Select overview

### Summary

svm-dr and snaplock compliance should be mentioned as not supported

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here:
https://docs.netapp.com/us-en/ontap-select/concept_ots_overview.html#ontap-features-not-supported-in-ontap-select
