### ISSUE TITLE
Recommended backup options

### ISSUE THREAD

**Issue by pdiddens** [NetAppDocs/ontap-select#220]
### Page URL

https://docs.netapp.com/us-en/ontap-select/reference_faq.html

### Page title

Frequently asked questions

### Summary

SVM DR is not supported with OTS and should be removed from the recommended backup options.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: 
https://docs.netapp.com/us-en/ontap-select/reference_faq.html#general
