### ISSUE TITLE
remove NetApp HCI

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/ontap-select#228]
### Page URL

https://docs.netapp.com/us-en/ontap-select/concept_stor_vsan_external.html

### Page title

VSAN and external array configurations

### Summary

"Virtual NAS (vNAS) deployments support ONTAP Select clusters on VSAN, some HCI products, NetApp HCI technology, and external array types of datastores. The underlying infrastructure of these configurations provide datastore resiliency."

we should remove the term "NetApp HCI technology" as this is EOA since more than one year. no need to mention it here.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here:
https://docs.netapp.com/us-en/ontap-select/concept_stor_vsan_external.html
