### ISSUE TITLE
ONTAP Select - invalid download instructions

### ISSUE THREAD

**Issue by pgbachman** [NetAppDocs/ontap-select#242]
### Page URL

https://docs.netapp.com/us-en/ontap-select/task_install_deploy.html

### Page title

Install ONTAP Select Deploy

### Summary

The layout of the home screen on the NetApp support site (NSS) has changed. The directions are no longer correct.

See attached document for recommended changes.
[2024-0209 OTS Invalid Download Directions.docx](https://github.com/NetAppDocs/ontap-select/files/14225462/2024-0209.OTS.Invalid.Download.Directions.docx)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @pgbachman, thank you for bringing this to our attention. We'll investigate and make any necessary documentation updates.

**Comment by netapp-ehoffman** [comment]
@pgbachman, thanks for making us aware of this and for sharing your recommendations for reworking. 

@netapp-cgoff, we ideally don't want to document the details of software downloads, given that we don't own the process (and our customers likely don't need to be coached through this). Let's minimize the details here.
