### ISSUE TITLE
Please add the ONTAP Select upgrade path to the manual.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap-select#244]
### Page URL

https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html

### Page title

Upgrade the ONTAP Select nodes

### Summary

For FAS/AFF, 
The ONTAP upgrade path is listed below.
https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths
![image](https://github.com/NetAppDocs/ontap-select/assets/68621663/935a8820-22b7-4736-8746-6e71d27b9719)

CVO has a different upgrade path.
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#how-to-upgrade
![image](https://github.com/NetAppDocs/ontap-select/assets/68621663/00eb8aa4-ff9a-495b-a001-07bd0226986c)

If ONTAP Select has the same upgrade path as FAS/AFF, please document this in the manual.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation by clarifying step four of the general procedure: https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html#general-procedure

**Comment by kanitani** [comment]
I couldn’t find the information I am expecting.
 Where can I find that information?
If I am not using the Upgrade Advisor, how can I find out about my upgrade path?

**Comment by netapp-cgoff** [comment]
Hi @kanitani - Thanks for reaching out. If you look under the overview topic, there is a sub-section called **Prepare for an ONTAP upgrade**. In this sub-section, you can find the upgrade paths topic which you linked in your original issue comment:
https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html 
I hope this helps!

**Comment by kanitani** [comment]
Could you please write in the manual that this content also applies to ONTAP Select?

**Comment by kanitani** [comment]
Hello?
I look forward to your comments.

**Comment by netapp-cgoff** [comment]
Hello, thanks again for your feedback. 

In step 4 of the general procedure you can now find the link directly to the upgrade paths topic and at the bottom of the page, the overview of the ONTAP upgrade process has been included in a new "Related information" section:
https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html#general-procedure 

I hope this helps and if you've anymore feedback, please let us know.

**Comment by kanitani** [comment]
Thanks!!
