### ISSUE TITLE
ONTAP Select Deploy download instructions are incorrect, customers did not succeed using the current steps shown

### ISSUE THREAD

**Issue by pgbachman** [NetAppDocs/ontap-select#246]
### Page URL

https://docs.netapp.com/us-en/ontap-select/task_install_deploy.html

### Page title

Install ONTAP Select Deploy

### Summary

In the section "Download the virtual machine image", under Steps, replace steps 1-7 with these:

1. Access the NetApp support site using a web browser and click the **Downloads** menu in the screen heading, and click **Downloads**.
2. Under **All Products A-Z**, click the letter **O**.
3. Click the link titled **ONTAP Select**.
4. Click the **large blue button** for the latest release. You may also use the drop down below to select a specific version.
5. **Respond** to the Cautions, Review the End User License Agreement (EULA), and click **Accept & Continue.**
6. Select and download the appropriate package, responding to all prompts as needed. Use the **View and download checksums** link to validate the file download.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: https://docs.netapp.com/us-en/ontap-select/task_install_deploy.html#download-the-virtual-machine-image
