### ISSUE TITLE
ESXi 6.5 GA and ESXi 6.7 GA are reaching end of availability status.

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/ontap-select#253]
### Page URL

https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_hardware.html

### Page title

VMware hypervisor and hardware considerations

### Summary

> ESXi 6.5 GA and ESXi 6.7 GA are reaching end of availability status.

They reached it a while ago.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by scaleoutsean** [comment]
Also on the same page, there are recommendations to upgrade to some prehistoric vSphere 6.5 update.

**Comment by netapp-pcarriga** [comment]
Thank you @scaleoutsean for bringing this to our attention. We will investigate and provide an update here.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: 
https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_hardware.html#software-compatibility
