### ISSUE TITLE
Update ONTAP Select documentation with current releases of RHEL.

### ISSUE THREAD

**Issue by netapp-chrisgeb** [NetAppDocs/ontap-select#267]
### Page URL

https://docs.netapp.com/us-en/ontap-select/reference_chk_host_prep.html

### Page title

Host configuration and preparation checklist

### Summary

RHEL 7.x is no longer supported.  

Our IMT lists the following versions supported.
Rocky Linux 8.6 KVM 64-bit
Rocky Linux 8.7 KVM 64-bit
Rocky Linux 8.8 KVM 64-bit
Rocky Linux 8.9 KVM 64-bit
Rocky Linux 9.0 KVM 64-bit
Rocky Linux 9.1 KVM 64-bit
Rocky Linux 9.2 KVM 64-bit
Rocky Linux 9.3 KVM 64-bit
Rocky Linux 9.4 KVM 64-bit

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thank you @netapp-chrisgeb for bringing this to our attention. I will verify and then update you here.

**Comment by netapp-pcarriga** [comment]
Hi @netapp-chrisgeb, the references to RHEK 7.x have been removed from the ONTAP Select 9.15.1 and 9.14.1 versions of the documentation. Thank you again for bringing this issue to our attention.
