### ISSUE TITLE
There is insufficient information regarding the language settings of the Windows OS on which the vCenter Server runs.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap-select#269]
### Page URL

https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html

### Page title

Hypervisor host considerations

### Summary

The 9.12.1 manual contains the following note, but this note is no longer included in the 9.15.1 manual.
Is ONTAP Select Deploy 9.15.1 now compatible with Windows OS in languages ​​other than English?

https://docs.netapp.com/us-en/ontap-select-9121/reference_plan_dep_vmware.html
![{6FC1CDB0-601A-44D0-AC96-FF02606A81EC}](https://github.com/user-attachments/assets/933f25a6-4119-4553-ba3a-bdfb9d0724b1)

I would like to confirm this as soon as possible, so please let me know the correct information.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thank you @kanitani for raising this question. I will investigate and update you here.

**Comment by netapp-aaron-holt** [comment]
Assigned to this issue. Added _"documentation"_ label.

**Comment by netapp-aaron-holt** [comment]
Hi @kanitani thanks for your query.
I've investigated this issue and can confirm that you are correct. ONTAP Select Deploy 9.15.1 is compatible with Windows OS in languages other than English.

**Comment by kanitani** [comment]
Could you please add a note to the 9.15.1 section of the release notes stating that the language restrictions for the vCenter Server operating system have been removed?
Since this isn't explicitly stated, many users mistakenly believe the previous restrictions still apply, which is causing issues.

https://docs.netapp.com/us-en/ontap-select/reference_new_ots.html

**Comment by kanitani** [comment]
This information wasn't included in this PDF either. 

https://library.netapp.com/ecm/ecm_download_file/ECMLP3318065
<img width="814" height="493" alt="Image" src="https://github.com/user-attachments/assets/f8ab1e72-6b34-419f-bff9-a36b30266582" />

The PDF itself doesn't need to be corrected, but could you please correct just the 9.15.1 section under "What's New"?

**Comment by netapp-barbe** [comment]
I am reopening this issue for Paula.
